# Generated by Django 5.0.1 on 2024-02-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksprofile',
            options={'ordering': ['last_name'], 'verbose_name': 'Профиль(Задания)', 'verbose_name_plural': 'Профили(Задания)'},
        ),
    ]
